apiVersion: v1
kind: Pod
metadata:
  labels:
    name: postgres-pod
    app: demo-voting-app

spec:
  containers:
    - name: postgres-pod
      image: postgres:9.4
      ports:
        - containerPort: 5432