apiVersion: v1
kind: Pod
metadata:
  name: voting-result-pod
  labels:
    name: voiting-result-pod
    app: demo-voting-app

spec:
  containers:
    - name: voting-result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80